### ISSUE TITLE
✨ 投稿视频尚未支持 metadata 生成

### ISSUE THREAD

**Issue by PiraticAshin** [SigureMo/yutto#21]
### 问题简述

通过源码编译安装的 yutto 添加生成元数据文件的参数后报错，python 3.9 和 3.10 都不能正常运行。

### 复现方式

$ yutto --with-metadata https://www.bilibili.com/video/BV1BW411u7GY --debug
大会员  成功以大会员身份登录～
 DEBUG  ffmpeg -codecs
 DEBUG  ffmpeg -encoders
 DEBUG  ffmpeg -codecs
 DEBUG  ffmpeg -encoders
 投稿视频  柴可夫斯基第一钢琴协奏曲 郎朗 巴黎交响乐团 Piavo Jarvi
 INFO  [<class 'type'>]正在生成【柴可夫斯基第一钢琴协奏曲 郎朗 巴黎交响乐团 Piavo Jarvi】媒体描述文件
Traceback (most recent call last):
  File "/Users/pierce/Library/Python/3.10/bin/yutto", line 8, in <module>
    sys.exit(main())
  File "/Users/pierce/Library/Python/3.10/lib/python/site-packages/yutto/__main__.py", line 83, in main
    get.run(args)
  File "/Users/pierce/Library/Python/3.10/lib/python/site-packages/yutto/utils/functiontools/sync.py", line 31, in sync_func
    return asyncio.run(async_func(*args, **kwargs))
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/base_events.py", line 641, in run_until_complete
    return future.result()
  File "/Users/pierce/Library/Python/3.10/lib/python/site-packages/yutto/cli/get.py", line 174, in run
    save_episode_metadata_file(episode_data, metadata_type)
  File "/Users/pierce/Library/Python/3.10/lib/python/site-packages/yutto/utils/metadata.py", line 20, in save_episode_metadata_file
    metadata = episode_data["metadata"]
KeyError: 'metadata'

### 环境信息

-  OS: macOS Monterey 12.0.1
-  Python: 3.10.0 & 3.9.7 
-  yutto: yutto 2.0.0-beta.5 (通过源码编译安装)
-  FFmpeg: 4.4.1

**Comment by WhileKing** [comment]
暂时只支持番剧视频生成喔， 其他的还在路上
