### ISSUE TITLE
🐛  Connection reset by peer

### ISSUE THREAD

**Issue by mike-boost** [SigureMo/yutto#41]
### 问题简述

aiohttp.client_exceptions.ClientOSError: [Errno 54] Connection reset by peer

### 复现方式

$ yutto --batch https://www.bilibili.com/video/BV1av411r7yB\?from\=search\&seid\=4202061868728123298\&spm_id_from\=333.337.0.0                                                  [23:17:24]
 INFO  成功使用 uvloop 加速协程
 INFO  未提供 SESSDATA，无法下载会员专享剧集
 投稿视频  一天学完 PostgreSQL
 INFO  全 26 话
 INFO  已选择第 1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26 话
Traceback (most recent call last):
  File "/Users/xxxxx/opt/anaconda3/envs/python3_9_7/bin/yutto", line 8, in <module>
    sys.exit(main())
  File "/Users/xxxxx/opt/anaconda3/envs/python3_9_7/lib/python3.9/site-packages/yutto/__main__.py", line 87, in main
    batch_get.run(args)
  File "/Users/xxxxx/opt/anaconda3/envs/python3_9_7/lib/python3.9/site-packages/yutto/utils/functiontools/sync.py", line 31, in sync_func
    return asyncio.run(async_func(*args, **kwargs))
  File "/Users/xxxxx/opt/anaconda3/envs/python3_9_7/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "uvloop/loop.pyx", line 1501, in uvloop.loop.Loop.run_until_complete
  File "/Users/xxxxx/opt/anaconda3/envs/python3_9_7/lib/python3.9/site-packages/yutto/cli/batch_get.py", line 100, in run
    episode_data = await fetch_acg_video_data(
  File "/Users/xxxxx/opt/anaconda3/envs/python3_9_7/lib/python3.9/site-packages/yutto/cli/get.py", line 100, in fetch_acg_video_data
    danmaku = await get_danmaku(session, cid, args.danmaku_format) if not args.no_danmaku else EmptyDanmakuData
  File "/Users/xxxxx/opt/anaconda3/envs/python3_9_7/lib/python3.9/site-packages/yutto/api/danmaku.py", line 33, in get_danmaku
    danmaku_data["data"].append(await get_xml_danmaku(session, cid))
  File "/Users/xxxxx/opt/anaconda3/envs/python3_9_7/lib/python3.9/site-packages/yutto/api/danmaku.py", line 10, in get_xml_danmaku
    return await Fetcher.fetch_text(session, danmaku_api.format(cid=cid), encoding="utf-8")
  File "/Users/xxxxx/opt/anaconda3/envs/python3_9_7/lib/python3.9/site-packages/yutto/utils/fetcher.py", line 25, in connect_n_times
    return await connect_once(*args, **kwargs)
  File "/Users/xxxxx/opt/anaconda3/envs/python3_9_7/lib/python3.9/site-packages/yutto/utils/fetcher.py", line 65, in fetch_text
    async with session.get(url, proxy=Fetcher.proxy) as resp:
  File "/Users/xxxxx/opt/anaconda3/envs/python3_9_7/lib/python3.9/site-packages/aiohttp/client.py", line 1138, in __aenter__
    self._resp = await self._coro
  File "/Users/xxxxx/opt/anaconda3/envs/python3_9_7/lib/python3.9/site-packages/aiohttp/client.py", line 559, in _request
    await resp.start(conn)
  File "/Users/xxxxx/opt/anaconda3/envs/python3_9_7/lib/python3.9/site-packages/aiohttp/client_reqrep.py", line 898, in start
    message, payload = await protocol.read()  # type: ignore[union-attr]
  File "/Users/xxxxx/opt/anaconda3/envs/python3_9_7/lib/python3.9/site-packages/aiohttp/streams.py", line 616, in read
    await self._waiter
aiohttp.client_exceptions.ClientOSError: [Errno 54] Connection reset by peer

### 环境信息

-  OS: macOS 12.1
-  Python: Python 3.9.7
-  yutto: yutto 2.0.0-beta.7
-  FFmpeg: ffmpeg version 4.4.1

**Comment by SigureMo** [comment]
无法复现……重试也还是这样吗？

**Comment by WhileKing** [comment]
看下dns是不是设置的国内的，之前dns设置成谷歌的会有这个问题

**Comment by SigureMo** [comment]
emmmm，先 close 了，如果仍然有问题可以 reopen
