### ISSUE TITLE
🐛 

### ISSUE THREAD

**Issue by AlicLi** [SigureMo/yutto#5]
## 调用方式

`yutto -q 125 --vcodec hevc:hevc --no-danmaku -c <hidden> -n 8 -d <download_dir> https://www.bilibili.com/video/BV1RB4y1K7WS`

## 环境信息

-  OS: 操作系统类型及其版本号 `Ubuntu 20.04.2 LTS`
-  Python: Python 版本号 （`python --version`）`Python 3.9.5`
-  yutto: yutto 版本号（`yutto -v`）`yutto 2.0.0-beta.2`
-  FFmpeg: FFmpeg 版本号（`ffmpeg -version`）
 ```
ffmpeg version 4.2.4-1ubuntu0.1 Copyright (c) 2000-2020 the FFmpeg developers
built with gcc 9 (Ubuntu 9.3.0-10ubuntu2)
configuration: --prefix=/usr --extra-version=1ubuntu0.1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-avresample --disable-filter=resample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librsvg --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-nvenc --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
libavutil      56. 31.100 / 56. 31.100
libavcodec     58. 54.100 / 58. 54.100
libavformat    58. 29.100 / 58. 29.100
libavdevice    58.  8.100 / 58.  8.100
libavfilter     7. 57.100 /  7. 57.100
libavresample   4.  0.  0 /  4.  0.  0
libswscale      5.  5.100 /  5.  5.100
libswresample   3.  5.100 /  3.  5.100
libpostproc    55.  5.100 / 55.  5.100
 ```
-  如果是显示相关问题
   -  Shell: Shell 类型 (`echo $SHELL`)
   -  Terminal: 终端类型
-  Others: 其它信息

## 问题简述

下载成视频和音频的m4s文件，然后报错

```
INFO  成功使用 uvloop 加速协程
 大会员  成功以大会员身份登录～
 投稿视频  王刚美食游记：时隔多年再赴湖南永州，学习传统湘菜“血鸭”做法
 INFO  开始处理视频 王刚美食游记：时隔多年再赴湖南永州，学习传统湘菜“血鸭”做法
 INFO  共包含以下 12 个视频流：
 INFO    0 [AVC ] [3840x2160] < 4K 超清  > #1
 INFO  * 1 [HEVC] [3840x2160] < 4K 超清  > #1
 INFO    2 [AVC ] [1920x1080] <1080P 60帧> #1
 INFO    3 [HEVC] [1920x1080] <1080P 60帧> #1
 INFO    4 [AVC ] [1920x1080] <1080P 高清> #1
 INFO    5 [HEVC] [1920x1080] <1080P 高清> #1
 INFO    6 [AVC ] [1280x720 ] <720P 高清 > #1
 INFO    7 [HEVC] [1280x720 ] <720P 高清 > #1
 INFO    8 [AVC ] [ 852x480 ] <480P 清晰 > #1
 INFO    9 [HEVC] [ 852x480 ] <480P 清晰 > #1
 INFO   10 [HEVC] [ 640x360 ] <360P 流畅 > #1
 INFO   11 [AVC ] [ 640x360 ] <360P 流畅 > #1
 INFO  共包含以下 3 个音频流：
 INFO  * 0 [MP4A] <320kbps >
 INFO    1 [MP4A] < 64kbps >
 INFO    2 [MP4A] <128kbps >
 INFO  开始下载……
Traceback (most recent call last):━━━━━━━━━━━━━━━━ 462.17 MiB/463.97 MiB 4.90 MiB/s    
  File "/home/al/.local/bin/yutto", line 8, in <module>
    sys.exit(main())
  File "/home/al/.local/lib/python3.9/site-packages/yutto/__main__.py", line 80, in main
    get.run(args)
  File "/home/al/.local/lib/python3.9/site-packages/yutto/utils/functiontools/sync.py", line 31, in sync_func
    return asyncio.run(async_func(*args, **kwargs))
  File "/usr/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "uvloop/loop.pyx", line 1494, in uvloop.loop.Loop.run_until_complete
  File "/home/al/.local/lib/python3.9/site-packages/yutto/cli/get.py", line 168, in run
    await process_video_download(
  File "/home/al/.local/lib/python3.9/site-packages/yutto/processor/downloader.py", line 246, in process_video_download
    await download_video_and_audio(session, video, video_path, audio, audio_path, options)
  File "/home/al/.local/lib/python3.9/site-packages/yutto/processor/downloader.py", line 146, in download_video_and_audio
    await task
  File "/home/al/.local/lib/python3.9/site-packages/yutto/utils/asynclib.py", line 39, in worker
    await task
  File "/home/al/.local/lib/python3.9/site-packages/yutto/utils/fetcher.py", line 122, in download_file_with_offset
    async with session.get(
  File "/home/al/.local/lib/python3.9/site-packages/aiohttp/client.py", line 1117, in __aenter__
    self._resp = await self._coro
  File "/home/al/.local/lib/python3.9/site-packages/aiohttp/client.py", line 544, in _request
    await resp.start(conn)
  File "/home/al/.local/lib/python3.9/site-packages/aiohttp/client_reqrep.py", line 890, in start
    message, payload = await self._protocol.read()  # type: ignore
  File "/home/al/.local/lib/python3.9/site-packages/aiohttp/streams.py", line 604, in read
    await self._waiter
aiohttp.client_exceptions.ServerDisconnectedError: Server disconnected
```
## 预期行为

顺利下载成hevc的4K视频

**Comment by SigureMo** [comment]
看报错信息貌似是网络连接问题啊，重新下载试试呢？

另外，冒号后面的参数是用来强制使用 ffmpeg 转换的，在当前资源已经是 hevc 的情况下直接使用 copy 就好了，之后我考虑优化下这里

**Comment by AlicLi** [comment]
用不同的网络设置（没有用代理）尝试了几个4K视频 都是一样的错误 并且无法下载完成

另外说一下，最近bilili的下载，一直都无法识别视频标题（都会显示呐，我也不知道是什么标题呢~）1.4.3版本

**Comment by SigureMo** [comment]
唔，这个 ServerDisconnectedError 我之前没有遇到过，刚刚处理了下，那我现在直接 release 一个新版本吧

关于 bilili 的标题问题，在 1.4.8 应该就修复了，升级一下就好了

**Comment by AlicLi** [comment]
刚刚看了下 不知道为什么之前bilili更新一直没成功 谢谢了♪(･ω･)ﾉ
稍微我再试试yutto的新release

**Comment by SigureMo** [comment]
刚刚发版了，你再试试(๑>؂<๑）

```
pip install -U --pre yutto
```
